name: Hoc GitHub Actions Cung Thinh

on:
  push:
    branches: ["main"] # Có dấu cách sau dấu hai chấm và dấu ngoặc vuông

jobs:
  job_kiem_tra_code:
    runs-on: ubuntu-latest # Thụt vào 2 dấu cách so với chữ jobs

    steps: # Thụt vào 2 dấu cách so với chữ job_kiem_tra_code
      - name: Lay code ve may ao
        uses: actions/checkout@v4

      - name: Chay lenh thong bao
        run: echo "Chao Thinh! GitHub dang kiem tra code cho ban..."

      - name: Kiem tra phien ban .NET
        run: dotnet --version
